name: Public AUR thermalright-trcc-git

on:
  push:
    paths:
        - "thermalright-trcc-git/PKGBUILD"
  workflow_dispatch:

jobs:
  public_aur:
    runs-on: ubuntu-latest
    # if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v3
        with:
          pkgname: thermalright-trcc-git
          pkgbuild: thermalright-trcc-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR thermalright-trcc-git package
          ssh_keyscan_types: rsa,ecdsa,ed25519
          # updpkgsums: true
